#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: OpenWrt

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches: 
      - master
  schedule:
    - cron: 0 0 1 * *
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -yqq update
          sudo -E apt-get -yqq install build-essential asciidoc binutils bzip2 lib32gcc-s1 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
      - name: Download openwrt
        run: |
          git clone https://github.com/openwrt/openwrt.git
          cp .config ./openwrt/.config
          mv ./openwrt/* ./
      - name: Install Helloword
        run: |
          # echo "src-git helloworld https://github.com/fw876/helloworld" >> ./feeds.conf.default 
          rm -rf package/helloworld
          git clone --depth=1 https://github.com/fw876/helloworld.git package/helloworld
          git -C package/helloworld pull
          rm -rf package/helloworld
      - name: Install OpenClash
        run: |
          # svn co https://github.com/vernesong/OpenClash/trunk/luci-app-openclash package/luci-app-openclash
          $ mkdir package/luci-app-openclash
          # cd package/luci-app-openclash
          # git init
          # git remote add -f origin https://github.com/vernesong/OpenClash.git
          # git config core.sparsecheckout true
          # echo "luci-app-openclash" >> .git/info/sparse-checkout
          # git pull --depth 1 origin master
          # git branch --set-upstream-to=origin/master master
          # pushd luci-app-openclash/tools/po2lmo
          # make && sudo make install
          # popd
          mkdir package/openclash
          git clone --depth=1 https://github.com/vernesong/OpenClash.git
          git -C package/openclash pull
          rm -rf package/openclash
      - name: Install homeproxy
        run: |
          mkdir package/homeproxy
          git clone --depth=1 https://github.com/muink/luci-app-homeproxy.git package/homeproxy
          git -C package/homeproxy pull
          rm -rf package/homeproxy
      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: Costom configure file
        run: |
          make defconfig
      - name: Download package source code
        run: |
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;
      - name: Compile firmware
        run: |
          echo -e "$(nproc) thread build."
          make -j$(nproc) V=s
      - name : Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt_firmware
          path: bin/targets/
          
