#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: OpenWrt

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches: 
      - master
  schedule:
    - cron: 0 0 1 * *
  watch:
    types: started
    
env:
  #REPO_URL: https://github.com/openwrt/openwrt.git
  #REPO_BRANCH: openwrt-24.10
  OpenWRTDevice: Beryl_gl-mt3000
  #CONFIG_FILE: .config
  #TZ: Europe/Berlin
  
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -yqq update
          sudo -E apt-get -yqq install build-essential asciidoc binutils bzip2 lib32gcc-s1 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
      - name: Download openwrt
        run: |
          git clone https://github.com/openwrt/openwrt.git
          cp .config ./openwrt/.config
          mv ./openwrt/* ./
      - name: Install Helloword
        run: |
          echo "src-git helloworld https://github.com/fw876/helloworld" >> ./feeds.conf.default 
          
      - name: Install Mihomo
        run: |
          echo "src-git mihomo https://github.com/morytyann/OpenWrt-mihomo.git;main" >> ./feeds.conf.default
          
      - name: Install homeproxy
        run: |
          echo "src-git https://github.com/lxiaya/openwrt-homeproxy" >> ./feeds.conf.default
          
      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: Costom configure file
        run: |
          make defconfig
      - name: Download package source code
        run: |
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;
      - name: Compile firmware
        run: |
          echo -e "$(nproc) thread build."
          make -j$(nproc) V=s
      - name : Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt_firmware
          path: bin/targets/
              
      - name: build RelTag
        id: BuildRelTag
        run: | 
          #echo "RelTag=$OpenWRTDevice-(${{ env.BUILDINFO }})-(${{ env.NOW }})" >> $GITHUB_ENV
          echo "RelTag=${{ env.NOW }}_${{ env.OpenWRTDevice }}_@(${{ env.BUILDINFO }})" >> $GITHUB_ENV

      - name: Upload firmware to github
        uses: actions/upload-artifact@main
        with:
          name: OpenWrt_firmware-${{ env.OpenWRTDevice }}-${{ env.NOW }}
          path: ${{ env.FIRMWARE }}

      - name: Create a release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "${{ env.RelTag }}"
          automatic_release_tag: "${{ env.BUILDINFO }}"
          files: |
            ${{ env.FIRMWARE }}/*squashfs*.bin
            ${{ env.FIRMWARE }}/*.buildinfo
            ${{ env.FIRMWARE }}/*.manifest
            ${{ env.FIRMWARE }}/sha256sums
          
